# Generated by Django 5.1 on 2024-08-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LibMS", "0003_remove_faculty_books_borrowed_faculty_books_borrowed"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="email",
            field=models.EmailField(default="null", max_length=100),
        ),
    ]
