# Generated by Django 5.1.1 on 2024-09-16 13:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LibMS", "0005_faculty_is_first_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="books_borrowed",
        ),
        migrations.CreateModel(
            name="BookIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("due_date", models.DateTimeField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LibMS.book"
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LibMS.faculty"
                    ),
                ),
            ],
        ),
    ]
