# Generated by Django 5.1.1 on 2024-09-16 16:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LibMS", "0006_remove_faculty_books_borrowed_bookissue"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.IntegerField(choices=[(1, "Issued"), (0, "Returned")]),
                ),
                ("date_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LibMS.book"
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LibMS.faculty"
                    ),
                ),
            ],
        ),
    ]
