# Generated by Django 5.1 on 2024-08-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "book_id",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("book_name", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("count", models.IntegerField(default=1)),
                ("rack", models.CharField(max_length=10)),
                ("shelf", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("id_number", models.CharField(max_length=20, unique=True)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                (
                    "books_borrowed",
                    models.ManyToManyField(
                        blank=True, related_name="borrowers", to="LibMS.book"
                    ),
                ),
            ],
        ),
    ]
