# Generated by Django 5.1 on 2024-08-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LibMS", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("id_number", models.CharField(max_length=50, unique=True)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("books_borrowed", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="book",
            name="count",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="rack",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="book",
            name="shelf",
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
